/**
 * Terms of Service Page
 *
 * Legally required document explaining user rights and responsibilities.
 */

import React from "react";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export default function TermsPage() {
  const lastUpdated = "January 29, 2026";

  return (
    <div className="container mx-auto max-w-4xl px-4 py-12">
      <Card className="border-none bg-transparent shadow-none">
        <CardHeader className="text-center">
          <CardTitle className="text-4xl font-serif">Terms of Service</CardTitle>
          <p className="mt-2 text-muted-foreground">Last updated: {lastUpdated}</p>
          <div className="mt-6">
            <Button asChild variant="outline">
              <Link href="https://aurumdiary.com">Back to aurumdiary.com</Link>
            </Button>
          </div>
        </CardHeader>
        <CardContent className="prose prose-slate mt-8 max-w-none dark:prose-invert">
          <section>
            <h2 className="mt-6 text-2xl font-serif">1. Acceptance of Terms</h2>
            <p>
              By accessing Aurum Sanctuary (the "Application"), you agree to be bound by these Terms of
              Service. If you do not agree with these terms, do not use the Application.
            </p>
          </section>

          <section>
            <h2 className="mt-6 text-2xl font-serif">2. Service Description</h2>
            <p>
              Aurum Sanctuary is a mental wellness journaling service. We provide tools to capture your
              thoughts, analyze emotional patterns, and generate reflections based on your entries.
            </p>
          </section>

          <section>
            <h2 className="mt-6 text-2xl font-serif">3. Privacy and Encryption</h2>
            <p>Your privacy is a core priority.</p>
            <ul>
              <li>
                <strong>Client-side encryption:</strong> Your journal entries are encrypted on your device
                before they are sent to our servers.
              </li>
              <li>
                <strong>Admin-blind architecture:</strong> We use safeguards that prevent administrators from
                accessing your decryption keys.
              </li>
              <li>
                <strong>Processing:</strong> Aurum analysis runs in a secure environment where data is
                temporarily decrypted only for processing, without persistent plaintext storage.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mt-6 text-2xl font-serif">4. User Responsibilities</h2>
            <p>You are responsible for:</p>
            <ul>
              <li>Keeping your account credentials confidential.</li>
              <li>All activity under your account.</li>
              <li>Not using the service for illegal or harmful activities.</li>
            </ul>
          </section>

          <section>
            <h2 className="mt-6 text-2xl font-serif">5. Medical Disclaimer</h2>
            <p className="font-semibold text-amber-700 dark:text-amber-500">
              IMPORTANT: Aurum Sanctuary is not a medical or licensed mental health service.
            </p>
            <p>
              Content generated by the Aurum engine and Application tools is intended for personal reflection
              and general wellbeing. It is not a substitute for professional advice, diagnosis, or treatment.
              If you are in crisis or need medical support, contact a qualified professional or emergency
              services immediately.
            </p>
          </section>

          <section>
            <h2 className="mt-6 text-2xl font-serif">6. Subscriptions and Payments</h2>
            <p>
              Some features may require a paid subscription. Payment and cancellation terms are managed by
              our payment provider, Stripe.
            </p>
          </section>

          <section>
            <h2 className="mt-6 text-2xl font-serif">7. Changes to Terms</h2>
            <p>
              We may update these terms at any time. We will notify you of material changes in the
              Application or by email.
            </p>
          </section>

          <section className="mt-12 rounded-lg bg-slate-100 p-6 dark:bg-slate-900">
            <p className="text-sm italic">
              If you have questions about these terms, contact us from your account settings.
            </p>
          </section>
        </CardContent>
      </Card>
    </div>
  );
}
