/**
 * Insights Page
 * 
 * Displays weekly insights generated by the Insight Engine.
 */

'use client';

import { useEffect, useState } from 'react';
import { collection, query, orderBy, getDocs } from 'firebase/firestore';
import { firestore } from '@/lib/firebase/web-client';
import { useAuth } from '@/providers/auth-provider';
import { useSubscription } from '@/hooks/useSubscription';
import { InsightCard } from '@/components/insights/InsightCard';
import { PaywallModal } from '@/components/paywall/PaywallModal';
import { Skeleton } from '@/components/ui/skeleton';
import { Sparkles, Crown } from 'lucide-react';

interface Insight {
    id: string;
    insightText: string;
    periodStart: Date;
    periodEnd: Date;
    createdAt: Date;
    status: 'ready' | 'viewed';
}

export default function InsightsPage() {
    const { user } = useAuth();
    const { isPremium, loading: subscriptionLoading } = useSubscription();
    const [insights, setInsights] = useState<Insight[]>([]);
    const [loading, setLoading] = useState(true);
    const [isPaywallOpen, setIsPaywallOpen] = useState(false);

    useEffect(() => {
        if (!user) {
            setLoading(false);
            return;
        }

        const fetchInsights = async () => {
            try {
                const insightsRef = collection(firestore, 'users', user.uid, 'insights');
                const q = query(insightsRef, orderBy('periodStart', 'desc'));
                const snapshot = await getDocs(q);

                const fetchedInsights: Insight[] = snapshot.docs.map(doc => {
                    const data = doc.data();
                    return {
                        id: doc.id,
                        insightText: data.insightText,
                        periodStart: data.periodStart?.toDate() || new Date(),
                        periodEnd: data.periodEnd?.toDate() || new Date(),
                        createdAt: data.createdAt?.toDate() || new Date(),
                        status: data.status || 'ready',
                    };
                });

                setInsights(fetchedInsights);
            } catch (error) {
                console.error('Error fetching insights:', error);
            } finally {
                setLoading(false);
            }
        };

        fetchInsights();
    }, [user]);

    if (!user) {
        return (
            <div className="container max-w-4xl mx-auto px-4 py-12">
                <div className="text-center">
                    <h1 className="text-3xl font-serif text-[#8B4513] mb-4">Weekly Insights</h1>
                    <p className="text-[#8B4513] opacity-70">
                        Please sign in to view your insights.
                    </p>
                </div>
            </div>
        );
    }

    if (loading || subscriptionLoading) {
        return (
            <div className="container max-w-4xl mx-auto px-4 py-12">
                <h1 className="text-3xl font-serif text-[#8B4513] mb-8">Weekly Insights</h1>
                <div className="space-y-6">
                    <Skeleton className="h-48 w-full rounded-lg" />
                    <Skeleton className="h-48 w-full rounded-lg" />
                    <Skeleton className="h-48 w-full rounded-lg" />
                </div>
            </div>
        );
    }

    if (insights.length === 0) {
        // Calculate days until first insight
        const createdAt = user.metadata.creationTime
            ? new Date(user.metadata.creationTime)
            : new Date();
        const daysSinceSignup = Math.floor(
            (Date.now() - createdAt.getTime()) / (1000 * 60 * 60 * 24)
        );
        const daysUntilInsight = Math.max(0, 7 - daysSinceSignup);

        return (
            <div className="container max-w-4xl mx-auto px-4 py-12">
                <h1 className="text-3xl font-serif text-[#8B4513] mb-8">Weekly Insights</h1>

                <div className="bg-[#F5F5DC] border border-[#8B4513] rounded-lg p-12 text-center">
                    <Sparkles className="w-16 h-16 text-[#D4AF37] mx-auto mb-6" />
                    <h2 className="text-2xl font-serif text-[#8B4513] mb-4">
                        Your First Insight Awaits
                    </h2>
                    <p className="text-[#8B4513] opacity-70 mb-2">
                        {daysUntilInsight === 0
                            ? 'Your first weekly insight will arrive soon!'
                            : `Your first insight will arrive in ${daysUntilInsight} day${daysUntilInsight > 1 ? 's' : ''}.`
                        }
                    </p>
                    <p className="text-sm text-[#8B4513] opacity-60">
                        Keep journaling to help us understand your emotional patterns.
                    </p>
                </div>
            </div>
        );
    }

    return (
        <div className="container max-w-4xl mx-auto px-4 py-12">
            <div className="flex items-center justify-between mb-8">
                <div>
                    <h1 className="text-3xl font-serif text-[#8B4513] mb-2">Weekly Insights</h1>
                    <p className="text-[#8B4513] opacity-70">
                        Patterns and reflections from your journaling journey
                    </p>
                </div>
                {isPremium && (
                    <div className="flex items-center gap-2 px-3 py-1.5 bg-[#D4AF37]/10 border border-[#D4AF37]/30 rounded-full">
                        <Crown className="w-4 h-4 text-[#D4AF37]" />
                        <span className="text-sm font-medium text-[#D4AF37]">Premium Member</span>
                    </div>
                )}
            </div>

            <div className="space-y-6">
                {insights.map((insight) => (
                    <InsightCard
                        key={insight.id}
                        insight={insight}
                        isPremium={isPremium}
                        onShowPaywall={() => setIsPaywallOpen(true)}
                    />
                ))}
            </div>

            <PaywallModal
                isOpen={isPaywallOpen}
                onClose={() => setIsPaywallOpen(false)}
            />
        </div>
    );
}
