"use strict";
/**
 * Cloud Function: generateInsight
 *
 * Scheduled function that generates weekly insights for users.
 * Runs every Sunday at 9am UTC.
 *
 * For each eligible user (7+ days since signup, 3+ entries):
 * 1. Fetch DerivedMemoryLite
 * 2. Call DeepSeek API to generate insight
 * 3. Store insight in Firestore
 * 4. Create notification
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateInsight = void 0;
const scheduler_1 = require("firebase-functions/v2/scheduler");
const firestore_1 = require("firebase-admin/firestore");
const app_1 = require("firebase-admin/app");
// Initialize Firebase Admin
(0, app_1.initializeApp)();
const firestore = (0, firestore_1.getFirestore)();
/**
 * Call DeepSeek API to generate insight
 */
async function callDeepSeekForInsight(derivedMemoryLite) {
    const DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY;
    if (!DEEPSEEK_API_KEY) {
        throw new Error('DEEPSEEK_API_KEY not configured');
    }
    // Build prompt
    const systemPrompt = `You are an emotional pattern analyst for Aurum Sanctuary.

Your role is to generate weekly insights that reveal emotional patterns from journaling data.

Core Principles:
1. Be DESCRIPTIVE, NOT CAUSAL ("We observe..." not "This is because...")
2. NEVER give advice or recommendations
3. Focus on PATTERNS and RECURRING THEMES
4. Use CALM, NON-JUDGMENTAL language
5. Maximum 200 words

Remember: You are a mirror, not a guide. Reflect patterns, don't prescribe solutions.`;
    const userPrompt = buildUserPrompt(derivedMemoryLite);
    // Call DeepSeek API
    const response = await fetch('https://api.deepseek.com/v1/chat/completions', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${DEEPSEEK_API_KEY}`,
        },
        body: JSON.stringify({
            model: 'deepseek-chat',
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: userPrompt },
            ],
            max_tokens: 300,
            temperature: 0.7,
        }),
    });
    if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`DeepSeek API error: ${response.status} ${errorText}`);
    }
    const data = await response.json();
    const insight = data.choices?.[0]?.message?.content;
    if (!insight) {
        throw new Error('No insight generated by DeepSeek');
    }
    return insight.trim();
}
/**
 * Build user prompt from DerivedMemoryLite
 */
function buildUserPrompt(lite) {
    const { labels, totalEntries, avgWordsPerEntry } = lite;
    const labelsText = labels?.length > 0
        ? labels.join(', ')
        : 'No specific themes detected yet';
    return `Generate a weekly insight based on this journaling data:

**Journaling Activity:**
- Total Entries This Week: ${totalEntries || 0}
- Average Words per Entry: ${Math.round(avgWordsPerEntry || 0)}

**Observed Emotional Themes:**
${labelsText}

Generate a thoughtful, descriptive insight (max 200 words) that reflects on emotional patterns.`;
}
/**
 * Get week start and end dates
 */
function getWeekDates() {
    const now = new Date();
    const dayOfWeek = now.getDay(); // 0 = Sunday
    // Calculate last Sunday (start of week)
    const weekStart = new Date(now);
    weekStart.setDate(now.getDate() - dayOfWeek);
    weekStart.setHours(0, 0, 0, 0);
    // Calculate next Sunday (end of week)
    const weekEnd = new Date(weekStart);
    weekEnd.setDate(weekStart.getDate() + 7);
    weekEnd.setHours(23, 59, 59, 999);
    return { weekStart, weekEnd };
}
/**
 * Scheduled function: Generate insights for all eligible users
 *
 * Runs every Sunday at 9am UTC
 */
exports.generateInsight = (0, scheduler_1.onSchedule)({
    schedule: 'every sunday 09:00',
    timeZone: 'UTC',
    memory: '512MiB',
    timeoutSeconds: 540, // 9 minutes (max for scheduled functions)
}, async (event) => {
    console.log('🔍 Starting weekly insight generation...');
    try {
        // Get all users
        const usersSnapshot = await firestore.collection('users').get();
        console.log(`Found ${usersSnapshot.size} users`);
        let successCount = 0;
        let skipCount = 0;
        let errorCount = 0;
        for (const userDoc of usersSnapshot.docs) {
            const uid = userDoc.id;
            const userData = userDoc.data();
            try {
                // Check eligibility: 7+ days since signup
                const createdAt = userData.createdAt?.toDate();
                if (!createdAt) {
                    console.log(`⏭️  Skipping user ${uid}: No createdAt`);
                    skipCount++;
                    continue;
                }
                const daysSinceSignup = Math.floor((Date.now() - createdAt.getTime()) / (1000 * 60 * 60 * 24));
                if (daysSinceSignup < 7) {
                    console.log(`⏭️  Skipping user ${uid}: Only ${daysSinceSignup} days since signup`);
                    skipCount++;
                    continue;
                }
                // Fetch DerivedMemoryLite
                const liteDoc = await firestore
                    .doc(`users/${uid}/derivedMemory/lite`)
                    .get();
                if (!liteDoc.exists) {
                    console.log(`⏭️  Skipping user ${uid}: No DerivedMemoryLite`);
                    skipCount++;
                    continue;
                }
                const lite = liteDoc.data();
                // Check minimum entries (need at least 3 for meaningful insight)
                if (!lite || (lite.totalEntries || 0) < 3) {
                    console.log(`⏭️  Skipping user ${uid}: Only ${lite?.totalEntries || 0} entries`);
                    skipCount++;
                    continue;
                }
                // Generate insight with DeepSeek
                console.log(`🤖 Generating insight for user ${uid}...`);
                const insightText = await callDeepSeekForInsight(lite);
                // Get week dates
                const { weekStart, weekEnd } = getWeekDates();
                // Store insight
                await firestore.collection(`users/${uid}/insights`).add({
                    insightText,
                    periodStart: weekStart,
                    periodEnd: weekEnd,
                    createdAt: firestore_1.FieldValue.serverTimestamp(),
                    status: 'ready',
                });
                // Create notification
                await firestore.collection(`users/${uid}/notifications`).add({
                    type: 'insight_ready',
                    message: 'Your weekly insight is ready',
                    createdAt: firestore_1.FieldValue.serverTimestamp(),
                    read: false,
                });
                console.log(`✅ Insight generated for user ${uid}`);
                successCount++;
            }
            catch (userError) {
                console.error(`❌ Error generating insight for user ${uid}:`, userError);
                errorCount++;
            }
        }
        console.log(`\n📊 Insight generation complete:`);
        console.log(`   ✅ Success: ${successCount}`);
        console.log(`   ⏭️  Skipped: ${skipCount}`);
        console.log(`   ❌ Errors: ${errorCount}`);
    }
    catch (error) {
        console.error('❌ Fatal error in insight generation:', error);
        throw error;
    }
});
//# sourceMappingURL=generateInsight.js.map